name: Deploy React App (3dim) to GitHub Pages

on:
  push:
    branches:
      - main  # Run when you commit/push/edit on main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd 3dim
          npm install

      - name: Build project
        run: |
          cd 3dim
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./3dim/build
